server:
  port: 6000
spring:
  application:
    name: service-supplier-service
  profiles:
    active: dev
  jackson:
    serialization:
      fail-on-empty-beans: false  
    

  liquibase:
    enabled: false
    change-log: classpath:db/changelog/db.changelog-master.yaml